import { Injectable, Logger } from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';
import { History, Round, PairingResult } from '../interfaces/types';

@Injectable()
export class OutputService {
  private readonly logger = new Logger(OutputService.name);

  generateMarkdown(result: PairingResult): string {
    const date = new Date(result.date);
    const formattedDate = date.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    const nextDate = new Date(date);
    nextDate.setDate(nextDate.getDate() + 14);
    const formattedNextDate = nextDate.toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    });

    let md = `# ☕ Random Coffee Pairings\n\n`;
    md += `**Round ${result.round}** · ${formattedDate}\n\n`;
    md += `Time to grab a coffee with someone new! Here are this round's pairings:\n\n`;

    md += `| # | Person 1 | Person 2 | Done |\n`;
    md += `|---|----------|----------|------|\n`;

    result.pairings.forEach((pairing, index) => {
      const done = pairing.completed ? 'Yes' : '';
      md += `| ${index + 1} | ${pairing.pair[0]} | ${pairing.pair[1]} | ${done} |\n`;
    });

    if (result.sitOut) {
      md += `\n> 🪑 **Sitting out this round:** ${result.sitOut} _(don't worry, you're first up next time!)_\n`;
    }

    if (result.resetOccurred) {
      md += `\n> 🔄 _All possible pairings were exhausted — starting a fresh cycle!_\n`;
    }

    md += `\n---\n\n`;
    md += `*Generated automatically by Random Coffee ☕*\n`;
    md += `*Next round: ${formattedNextDate}*\n`;

    return md;
  }

  generateMarkdownFromRound(round: Round): string {
    const date = new Date(round.date);
    const formattedDate = date.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    const nextDate = new Date(date);
    nextDate.setDate(nextDate.getDate() + 14);
    const formattedNextDate = nextDate.toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    });

    let md = `# ☕ Random Coffee Pairings\n\n`;
    md += `**Round ${round.round}** · ${formattedDate}\n\n`;
    md += `Time to grab a coffee with someone new! Here are this round's pairings:\n\n`;

    md += `| # | Person 1 | Person 2 | Done |\n`;
    md += `|---|----------|----------|------|\n`;

    round.pairings.forEach((pairing, index) => {
      const done = pairing.completed ? 'Yes' : '';
      md += `| ${index + 1} | ${pairing.pair[0]} | ${pairing.pair[1]} | ${done} |\n`;
    });

    if (round.sitOut) {
      md += `\n> 🪑 **Sitting out this round:** ${round.sitOut} _(don't worry, you're first up next time!)_\n`;
    }

    md += `\n---\n\n`;
    md += `*Generated automatically by Random Coffee ☕*\n`;
    md += `*Next round: ${formattedNextDate}*\n`;

    return md;
  }

  writeMarkdownFile(content: string, date: string, outputDir?: string): string {
    const dir = outputDir ?? path.join(process.cwd(), 'pairings');
    fs.mkdirSync(dir, { recursive: true });

    const filePath = path.join(dir, `${date}.md`);
    fs.writeFileSync(filePath, content, 'utf-8');

    this.logger.log(`Pairings written to ${filePath}`);
    return filePath;
  }

  generateSiteHtml(history: History): string {
    const rounds = [...history.rounds].sort((a, b) => b.round - a.round);

    const dropdownOptions = rounds
      .map(
        (r) =>
          `<option value="round-${r.round}">Round ${r.round} — ${this.formatShortDate(r.date)}${r.round === rounds[0]?.round ? ' (current)' : ''}</option>`,
      )
      .join('\n          ');

    const sections = rounds
      .map((r, i) => this.generateRoundHtml(r, i === 0))
      .join('\n');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Random Coffee ☕</title>
  <style>${this.generateCss()}</style>
</head>
<body>
  <div class="container">
    <header>
      <h1>☕ Random Coffee</h1>
      ${rounds.length > 0 ? `<select id="round-select" onchange="showRound(this.value)">
          ${dropdownOptions}
        </select>` : ''}
    </header>
    <main>
      ${rounds.length === 0 ? '<p class="empty">No pairing rounds yet. Run <code>generate</code> to get started!</p>' : sections}
    </main>
    <footer>Generated by Random Coffee ☕</footer>
  </div>
  <script>${this.generateJs()}</script>
</body>
</html>`;
  }

  writeSitePage(history: History): string {
    const dir = path.join(process.cwd(), 'docs');
    fs.mkdirSync(dir, { recursive: true });

    const html = this.generateSiteHtml(history);
    const filePath = path.join(dir, 'index.html');
    fs.writeFileSync(filePath, html, 'utf-8');

    this.logger.log(`Site written to ${filePath}`);
    return filePath;
  }

  private generateRoundHtml(round: Round, isCurrent: boolean): string {
    const date = this.formatShortDate(round.date);
    const rows = round.pairings
      .map(
        (p, i) => {
          const checked = p.completed ? ' checked' : '';
          return `          <tr><td>${i + 1}</td><td>${this.escapeHtml(p.pair[0])}</td><td>${this.escapeHtml(p.pair[1])}</td><td class="done-cell"><input type="checkbox" class="done-check" data-round="${round.round}" data-pair="${i + 1}"${checked}></td></tr>`;
        },
      )
      .join('\n');

    const sitOut = round.sitOut
      ? `\n        <p class="sit-out">🪑 Sitting out: <strong>${this.escapeHtml(round.sitOut)}</strong></p>`
      : '';

    return `      <section id="round-${round.round}" class="round"${isCurrent ? '' : ' style="display:none"'}>
        <h2>Round ${round.round} <span class="date">${date}</span></h2>
        <table>
          <thead><tr><th>#</th><th>Person 1</th><th>Person 2</th><th>Done</th></tr></thead>
          <tbody>
${rows}
          </tbody>
        </table>${sitOut}
      </section>`;
  }

  private generateCss(): string {
    return `
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #faf6f1; color: #333; min-height: 100vh; display: flex; justify-content: center; }
    .container { max-width: 700px; width: 100%; padding: 2rem 1rem; }
    header { text-align: center; margin-bottom: 2rem; }
    h1 { color: #6f4e37; font-size: 1.8rem; margin-bottom: 1rem; }
    select { padding: 0.5rem 1rem; border: 1px solid #d4c5b2; border-radius: 6px; background: #fff; color: #6f4e37; font-size: 0.95rem; cursor: pointer; }
    select:focus { outline: 2px solid #6f4e37; }
    .round { background: #fff; border-radius: 10px; padding: 1.5rem; box-shadow: 0 2px 8px rgba(111,78,55,0.1); margin-bottom: 1rem; }
    h2 { color: #6f4e37; font-size: 1.3rem; margin-bottom: 1rem; }
    .date { font-weight: normal; font-size: 0.9rem; color: #8b7355; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; padding: 0.6rem 0.8rem; border-bottom: 2px solid #6f4e37; color: #6f4e37; font-size: 0.85rem; text-transform: uppercase; }
    td { padding: 0.6rem 0.8rem; border-bottom: 1px solid #eee; }
    tbody tr:nth-child(even) { background: #faf6f1; }
    .sit-out { margin-top: 1rem; padding: 0.7rem 1rem; background: #faf6f1; border-radius: 6px; font-size: 0.9rem; }
    .empty { text-align: center; color: #8b7355; padding: 2rem; }
    code { background: #eee; padding: 0.15rem 0.4rem; border-radius: 3px; font-size: 0.9em; }
    footer { text-align: center; color: #8b7355; font-size: 0.85rem; margin-top: 2rem; }
    .done-cell { text-align: center; }
    .done-check { width: 18px; height: 18px; cursor: pointer; accent-color: #6f4e37; }
    .done-check:disabled { cursor: wait; }
    .status-indicator { display: inline-block; margin-left: 4px; font-size: 0.8rem; }
  `;
  }

  private generateJs(): string {
    return `
    var REPO_OWNER = 'tonyhsap';
    var REPO_NAME = 'random-coffee-generator';
    var WORKFLOW_FILE = 'mark-coffee.yml';
    var PAT_KEY = 'coffee_github_pat';
    var CACHE_KEY = 'coffee_done_cache';

    function showRound(id) {
      document.querySelectorAll('.round').forEach(function(s) { s.style.display = 'none'; });
      var el = document.getElementById(id);
      if (el) el.style.display = '';
      history.replaceState(null, '', '#' + id);
    }

    function getCache() {
      try { return JSON.parse(localStorage.getItem(CACHE_KEY) || '{}'); } catch(e) { return {}; }
    }

    function setCache(roundNum, pairIdx, val) {
      var cache = getCache();
      cache[roundNum + '-' + pairIdx] = val;
      localStorage.setItem(CACHE_KEY, JSON.stringify(cache));
    }

    function applyCachedState() {
      var cache = getCache();
      document.querySelectorAll('.done-check').forEach(function(cb) {
        var key = cb.dataset.round + '-' + cb.dataset.pair;
        if (cache.hasOwnProperty(key)) {
          cb.checked = cache[key];
        }
      });
    }

    function getPat() {
      var pat = localStorage.getItem(PAT_KEY);
      if (pat) return pat;
      pat = prompt('Enter a GitHub Personal Access Token with actions:write scope to toggle completion status.\\n\\nThis is stored in your browser\\'s localStorage only.');
      if (pat) {
        localStorage.setItem(PAT_KEY, pat.trim());
        return pat.trim();
      }
      return null;
    }

    function triggerWorkflow(roundNum, pairIdx, cb) {
      var pat = getPat();
      if (!pat) {
        cb.checked = !cb.checked;
        return;
      }

      cb.disabled = true;
      var indicator = cb.parentNode.querySelector('.status-indicator');
      if (!indicator) {
        indicator = document.createElement('span');
        indicator.className = 'status-indicator';
        cb.parentNode.appendChild(indicator);
      }
      indicator.textContent = '...';

      setCache(roundNum, pairIdx, cb.checked);

      var url = 'https://api.github.com/repos/' + REPO_OWNER + '/' + REPO_NAME + '/actions/workflows/' + WORKFLOW_FILE + '/dispatches';
      fetch(url, {
        method: 'POST',
        headers: {
          'Authorization': 'Bearer ' + pat,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          ref: 'main',
          inputs: {
            round: String(roundNum),
            pair: String(pairIdx)
          }
        })
      }).then(function(resp) {
        if (resp.status === 204) {
          indicator.textContent = 'OK';
        } else if (resp.status === 401 || resp.status === 403) {
          localStorage.removeItem(PAT_KEY);
          indicator.textContent = 'Auth error';
          cb.checked = !cb.checked;
          setCache(roundNum, pairIdx, cb.checked);
        } else {
          indicator.textContent = 'Error';
          cb.checked = !cb.checked;
          setCache(roundNum, pairIdx, cb.checked);
        }
        cb.disabled = false;
        setTimeout(function() { indicator.textContent = ''; }, 3000);
      }).catch(function() {
        indicator.textContent = 'Network error';
        cb.checked = !cb.checked;
        setCache(roundNum, pairIdx, cb.checked);
        cb.disabled = false;
        setTimeout(function() { indicator.textContent = ''; }, 3000);
      });
    }

    document.addEventListener('change', function(e) {
      if (e.target && e.target.classList.contains('done-check')) {
        triggerWorkflow(e.target.dataset.round, e.target.dataset.pair, e.target);
      }
    });

    (function() {
      var hash = location.hash.replace('#', '');
      if (hash && document.getElementById(hash)) {
        showRound(hash);
        var sel = document.getElementById('round-select');
        if (sel) sel.value = hash;
      }
      applyCachedState();
    })();
  `;
  }

  private formatShortDate(dateStr: string): string {
    const d = new Date(dateStr + 'T00:00:00');
    return d.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  }

  private escapeHtml(str: string): string {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
}
